name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
        
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Build
      run: swift build -v
      
    - name: Run Tests
      run: swift test -v
      
    - name: Integration Test
      run: ./test-integration.sh

  lint:
    name: Lint
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
        
    - name: Swift Format Check
      run: |
        if command -v swift-format >/dev/null 2>&1; then
          swift-format lint --recursive Sources/
        else
          echo "swift-format not available, skipping lint"
        fi

  compatibility:
    name: Compatibility Test
    runs-on: macos-14
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
        
    - name: Build and Test
      run: |
        swift build -v
        swift test -v
